behaviors:
  Tracker:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 100000
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 50000000
    time_horizon: 256
    summary_freq: 10000

environment_parameters:

  movement_multiplier:
    curriculum:
      - name: easy
        completion_criteria:
          measure: progress
          behavior: Tracker
          threshold: 0.2
          min_lesson_length: 100
        value: 0.5

      - name: medium
        completion_criteria:
          measure: progress
          behavior: Tracker
          threshold: 0.6
          min_lesson_length: 100
          require_reset: true
        value: 2.0

      - name: hard
        value: 5.0


  number_of_targets:
    curriculum:
      - name: easy
        completion_criteria:
          measure: progress
          behavior: Tracker
          threshold: 0.2
          min_lesson_length: 100
        value: 1

      - name: medium
        completion_criteria:
          measure: progress
          behavior: Tracker
          threshold: 0.6
          min_lesson_length: 100
          require_reset: true
        value: 5

      - name: hard
        value: 20


  friendly_ratio:
    curriculum:
      - name: easy
        completion_criteria:
          measure: progress
          behavior: Tracker
          threshold: 0.2
          min_lesson_length: 100
        value: 0.0   # only enemies (forces shooting behaviour learning)

      - name: medium
        completion_criteria:
          measure: progress
          behavior: Tracker
          threshold: 0.6
          min_lesson_length: 100
          require_reset: true
        value: 0.2   # introduces risk

      - name: hard
        value: 0.4